# -*- mode: ruby -*-
# vi: set ft=ruby :
require '../vagrant_conf.rb'
include SharedVagrantSettings

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  SharedVagrantSettings.configure config

  #Any local settings go here
  config.vm.provision :shell, :path => "provisioning/bootstrap.sh"

end
