# -*- mode: ruby -*-
# vi: set ft=ruby :
require '../vagrant_conf.rb'
include SharedVagrantSettings

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  SharedVagrantSettings.configure config

  #Chef-Solo provisioning
  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
    config.omnibus.chef_version = :latest
    chef.log_level = :debug
    chef.add_recipe "7db7w-configure::riak"
    # You may also specify custom JSON attributes:
    # chef.json = { :mysql_password => "foo" }
  end

end
